<script lang="ts">
import { onMount } from 'svelte';
import * as pdfjsLib from 'pdfjs-dist';
import { FolderPlus, FileText, Search, ArrowLeft, Trash2, Music, Grid2X2, List, BookOpen, MoreHorizontal, Clock3 } from 'lucide-svelte';
import { db } from './db';
import type { ScoreItem } from './types';

let { onSelectScore }: { onSelectScore: (score: ScoreItem) => void } = $props();
let scores=$state<ScoreItem[]>([]), searchQuery=$state(''), isProcessing=$state(false), selectedComposerFolder=$state<string|null>(null), viewMode=$state<'grid'|'list'>('grid'), sortMode=$state<'recent'|'title'>('recent');

onMount(async()=>{scores=await db.scores.orderBy('addedAt').reverse().toArray();});
async function createThumbnail(file:File){const buffer=await file.arrayBuffer();const doc=await pdfjsLib.getDocument({data:new Uint8Array(buffer)}).promise;const totalPages=doc.numPages;const page=await doc.getPage(1);const viewport=page.getViewport({scale:.45});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)return{thumbnailUrl:undefined,totalPages};await page.render({canvasContext:ctx,viewport}).promise;return{thumbnailUrl:canvas.toDataURL('image/jpeg',.78),totalPages};}
async function handleFolderSelect(e:Event){const input=e.target as HTMLInputElement;if(!input.files?.length)return;isProcessing=true;try{for(const file of Array.from(input.files)){if(!file.name.toLowerCase().endsWith('.pdf'))continue;const parts=(file.webkitRelativePath||file.name).split('/');const composer=parts.length>=2?parts[parts.length-2]:'Unknown Composer';const title=file.name.replace(/\.pdf$/i,'');let thumbnailUrl:string|undefined,totalPages=1;try{({thumbnailUrl,totalPages}=await createThumbnail(file));}catch(err){console.warn('PDF preview warning:',file.name,err);}const score:ScoreItem={id:`${file.name}-${file.lastModified}-${Math.random()}`,title,composer,pdfBlob:file,thumbnailUrl,totalPages,addedAt:Date.now()};await db.scores.put(score);scores=[score,...scores];}}finally{isProcessing=false;input.value='';}}
async function deleteScore(id:string,e:MouseEvent){e.stopPropagation();await db.scores.delete(id);await db.annotations.where('scoreId').equals(id).delete();scores=scores.filter(s=>s.id!==id);}
const filteredScores=$derived(scores.filter(s=>!selectedComposerFolder||s.composer===selectedComposerFolder).filter(s=>{const q=searchQuery.toLowerCase().trim();return !q||s.title.toLowerCase().includes(q)||s.composer.toLowerCase().includes(q);}).sort((a,b)=>sortMode==='title'?a.title.localeCompare(b.title):b.addedAt-a.addedAt));
const composersMap=$derived.by(()=>{const map:Record<string,ScoreItem[]>={};const q=searchQuery.toLowerCase().trim();for(const s of scores){if(q&&!s.title.toLowerCase().includes(q)&&!s.composer.toLowerCase().includes(q))continue;(map[s.composer||'Unknown Composer']||=[]).push(s);}return map;});
function pages(n:number){return `${n} ${n===1?'page':'pages'}`;}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
</script>

<div class="flex-1 flex flex-col p-5 sm:p-7 max-w-7xl w-full mx-auto overflow-hidden">
<header class="flex flex-col lg:flex-row lg:items-center justify-between gap-5 pb-5 border-b border-neutral-800">
<div class="flex items-center gap-3 min-w-0">{#if selectedComposerFolder}<button onclick={()=>selectedComposerFolder=null} class="p-2.5 rounded-xl bg-neutral-900 border border-neutral-800 hover:bg-neutral-800"><ArrowLeft size={18}/></button>{/if}<div class="min-w-0"><div class="flex items-center gap-2"><BookOpen size={18} class="text-blue-400"/><h1 class="text-2xl sm:text-3xl font-semibold tracking-tight truncate">{selectedComposerFolder||'Music Library'}</h1></div><p class="text-sm text-neutral-500 mt-1">{selectedComposerFolder?`${filteredScores.length} ${filteredScores.length===1?'score':'scores'}`:'Your local sheet-music collection'}</p></div></div>
<label class="inline-flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-4 py-2.5 rounded-xl cursor-pointer font-medium transition"><FolderPlus size={18}/>{isProcessing?'Importing…':'Import folder'}<input type="file" webkitdirectory directory multiple accept="application/pdf" onchange={handleFolderSelect} disabled={isProcessing} class="hidden"/></label>
</header>
<div class="flex flex-col sm:flex-row gap-3 my-5"><div class="relative flex-1"><Search size={17} class="absolute left-3.5 top-1/2 -translate-y-1/2 text-neutral-500"/><input bind:value={searchQuery} placeholder="Search scores and composers…" class="w-full bg-neutral-900 border border-neutral-800 rounded-xl pl-10 pr-4 py-3 text-sm outline-none focus:border-blue-500"/></div>{#if selectedComposerFolder}<select bind:value={sortMode} class="bg-neutral-900 border border-neutral-800 rounded-xl px-3 text-sm text-neutral-300 outline-none"><option value="recent">Recently added</option><option value="title">Title</option></select><div class="flex bg-neutral-900 border border-neutral-800 rounded-xl p-1"><button onclick={()=>viewMode='grid'} class="p-2 rounded-lg {viewMode==='grid'?'bg-neutral-800 text-white':'text-neutral-500'}"><Grid2X2 size={16}/></button><button onclick={()=>viewMode='list'} class="p-2 rounded-lg {viewMode==='list'?'bg-neutral-800 text-white':'text-neutral-500'}"><List size={16}/></button></div>{/if}</div>
<div class="flex-1 overflow-y-auto pr-1">
{#if scores.length===0}<div class="h-72 flex flex-col items-center justify-center border border-dashed border-neutral-800 rounded-3xl text-neutral-500 gap-3"><Music size={38}/><p>No scores imported yet.</p><p class="text-xs text-neutral-600">Import a folder of PDFs to build your library.</p></div>
{:else if !selectedComposerFolder}<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
{#each Object.entries(composersMap).sort(([a],[b])=>a.localeCompare(b)) as [composer,items]}
<button onclick={()=>selectedComposerFolder=composer} class="group text-left relative rounded-2xl border border-neutral-800 bg-neutral-900/70 hover:bg-neutral-900 hover:border-neutral-700 overflow-hidden transition shadow-sm">
<div class="h-32 relative bg-neutral-950 overflow-hidden">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(59,130,246,.14),transparent_45%),radial-gradient(circle_at_80%_80%,rgba(168,85,247,.12),transparent_50%)]"></div>
<div class="absolute inset-x-5 bottom-[-20px] flex items-end gap-2 opacity-80 group-hover:translate-y-[-3px] transition-transform"><div class="w-20 h-28 bg-neutral-800 border border-neutral-700 rounded-t-md rotate-[-7deg] shadow-xl"></div><div class="w-20 h-28 bg-neutral-700 border border-neutral-600 rounded-t-md rotate-[2deg] shadow-2xl flex items-center justify-center"><FileText size={25} class="text-neutral-400"/></div><div class="w-20 h-28 bg-neutral-800 border border-neutral-700 rounded-t-md rotate-[7deg] shadow-xl"></div></div>
<div class="absolute top-4 right-4 px-2.5 py-1 rounded-full bg-neutral-900/90 border border-neutral-700 text-[11px] text-neutral-400">{items.length} {items.length===1?'score':'scores'}</div>
</div>
<div class="p-4 pt-5 flex items-center justify-between gap-3"><div class="min-w-0"><h2 class="font-semibold text-neutral-100 truncate group-hover:text-blue-300">{composer}</h2><p class="text-xs text-neutral-500 mt-1">Open collection</p></div><div class="w-9 h-9 rounded-xl bg-neutral-800 border border-neutral-700 flex items-center justify-center text-xs font-semibold text-neutral-400">{initials(composer)}</div></div>
</button>
{/each}</div>
{:else if filteredScores.length===0}<div class="h-56 flex items-center justify-center text-neutral-500">No scores match your search.</div>
{:else if viewMode==='list'}<div class="rounded-2xl border border-neutral-800 overflow-hidden divide-y divide-neutral-800 bg-neutral-900/60">{#each filteredScores as score}<div role="button" tabindex="0" onclick={()=>onSelectScore(score)} class="flex items-center gap-4 p-3.5 text-left hover:bg-neutral-800/70 transition group cursor-pointer"><div class="w-12 h-16 rounded-lg bg-neutral-950 overflow-hidden border border-neutral-800 shrink-0 flex items-center justify-center">{#if score.thumbnailUrl}<img src={score.thumbnailUrl} alt="" class="w-full h-full object-cover object-top"/>{:else}<FileText size={23} class="text-neutral-600"/>{/if}</div><div class="min-w-0 flex-1"><div class="text-sm font-semibold text-neutral-200 truncate group-hover:text-blue-300">{score.title}</div><div class="flex items-center gap-3 text-xs text-neutral-500 mt-1"><span>{pages(score.totalPages)}</span><span class="inline-flex items-center gap-1"><Clock3 size={12}/>{new Date(score.addedAt).toLocaleDateString()}</span></div></div><button onclick={e=>deleteScore(score.id,e)} class="p-2 text-neutral-500 hover:text-red-400 opacity-0 group-hover:opacity-100"><Trash2 size={16}/></button></div>{/each}</div>
{:else}<div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">{#each filteredScores as score}<div class="group relative rounded-2xl bg-neutral-900 border border-neutral-800 hover:border-neutral-700 overflow-hidden transition"><button onclick={()=>onSelectScore(score)} class="w-full text-left"><div class="aspect-[3/4] bg-neutral-950 p-2 flex items-center justify-center border-b border-neutral-800">{#if score.thumbnailUrl}<img src={score.thumbnailUrl} alt="" class="max-w-full max-h-full object-contain shadow-lg"/>{:else}<FileText size={32} class="text-neutral-700"/>{/if}</div><div class="p-3.5"><h3 class="text-sm font-medium text-neutral-100 truncate group-hover:text-blue-300">{score.title}</h3><div class="text-xs text-neutral-500 mt-1">{pages(score.totalPages)}</div></div></button><button onclick={e=>deleteScore(score.id,e)} title="Delete" class="absolute top-2 right-2 p-2 rounded-lg bg-neutral-900/90 border border-neutral-700 text-neutral-500 hover:text-red-400 opacity-0 group-hover:opacity-100 transition"><Trash2 size={15}/></button></div>{/each}</div>{/if}
</div>
</div>
