<script lang="ts">
	import { onMount, tick } from 'svelte';
	import * as pdfjsLib from 'pdfjs-dist';
	import { db } from './db';
	import type { ScoreItem, Stroke, SymbolStamp, TextNote } from './types';
	import { MUSIC_SYMBOLS, MUSIC_SYMBOL_CATEGORIES, type MusicSymbol } from './musicSymbols';
	import { ArrowLeft, ChevronLeft, ChevronRight, PenTool, Highlighter, Eraser, Type, Undo2, Redo2, ZoomIn, ZoomOut, MousePointer2, Minus, ArrowUpRight, BookOpen, Maximize2, PanelLeft, X, Trash2, Bookmark, BookmarkCheck, Settings2, Grid3X3, Timer, Mic2, Plus, MinusCircle } from 'lucide-svelte';

	let { score, onClose }: { score: ScoreItem; onClose: () => void } = $props();
	type Tool = 'move' | 'pen' | 'highlighter' | 'eraser' | 'text' | 'line' | 'arrow' | 'symbol';
	type FitMode = 'page' | 'width' | 'height' | 'free';
	type Snapshot = { strokes: Stroke[]; stamps: SymbolStamp[]; notes: TextNote[] };

	class BlobRangeTransport extends pdfjsLib.PDFDataRangeTransport {
		private blob: Blob;
		private pending = new Map<string, Promise<void>>();
		constructor(blob: Blob){super(blob.size,null,false,'score.pdf');this.blob=blob;}
		requestDataRange(begin:number,end:number){
			const key=`${begin}:${end}`; if(this.pending.has(key))return;
			const request=this.blob.slice(begin,end).arrayBuffer().then(buffer=>this.onDataRange(begin,new Uint8Array(buffer))).catch(error=>this.abort(error));
			this.pending.set(key,request); void request.finally(()=>this.pending.delete(key));
		}
		abort(_reason?:unknown){this.pending.clear();}
	}

	let pdfDoc = $state<pdfjsLib.PDFDocumentProxy | null>(null), rangeTransport: BlobRangeTransport | null = null;
	let current = $state(1), dual = $state(false), zoom = $state(1), fitMode = $state<FitMode>('page');
	let tool = $state<Tool>('move'), color = $state('#ef4444'), strokeWidth = $state(3);
	let annotations = $state<Record<number, Stroke[]>>({}), stamps = $state<Record<number, SymbolStamp[]>>({}), notes = $state<Record<number, TextNote[]>>({});
	let history = $state<Record<number, Snapshot[]>>({}), historyIndex = $state<Record<number, number>>({});
	let annotationOpen = $state(false), readingMode = $state(false), settingsOpen = $state(false), symbolsOpen = $state(false), bookmarked = $state(false), controlsVisible = $state(true), pageInput = $state('1');
	let utility: 'none' | 'metronome' | 'tuner' = $state('none');
	let host = $state<HTMLElement | null>(null), leftPdf = $state<HTMLCanvasElement | null>(null), rightPdf = $state<HTMLCanvasElement | null>(null), leftInk = $state<HTMLCanvasElement | null>(null), rightInk = $state<HTMLCanvasElement | null>(null);
	let renderId = 0, resizeTimer: ReturnType<typeof setTimeout> | undefined, renderBusy = $state(false), renderError = $state('');
	let metronomeBpm = $state(80), metronomeRunning = $state(false), metronomeBeat = $state(0), metroTimer: ReturnType<typeof setInterval> | undefined, audioContext: AudioContext | null = null;
	let tunerRunning = $state(false), tunerNote = $state('--'), tunerCents = $state(0), tunerFrequency = $state(0), tunerError = $state('');
	let tunerStream: MediaStream | null = null, analyser: AnalyserNode | null = null, tunerFrame = 0;
	let selectedSymbolCategory = $state('Accidentals'), selectedSymbol: MusicSymbol | null = $state(null);
	const colors = ['#ef4444', '#2563eb', '#16a34a', '#eab308', '#9333ea', '#111827'];

	onMount(() => {
		void loadScore();
		try{const saved=localStorage.getItem(`sonora-viewer-${score.id}`);if(saved){const s=JSON.parse(saved);bookmarked=!!s.bookmarked;zoom=typeof s.zoom==='number'?s.zoom:1;dual=!!s.dual;}}catch{}
		return()=>{pdfDoc?.destroy();rangeTransport?.abort();stopMetronome();stopTuner();if(audioContext)void audioContext.close();};
	});

	async function loadScore(){
		renderError='';renderBusy=true;
		try{
			rangeTransport=new BlobRangeTransport(score.pdfBlob);
			pdfDoc=await pdfjsLib.getDocument({range:rangeTransport,rangeChunkSize:256*1024,disableStream:true,disableAutoFetch:true,isEvalSupported:false}).promise;
			const records=await db.annotations.where('scoreId').equals(score.id).toArray();
			for(const r of records){annotations[r.pageNum]=r.strokes||[];stamps[r.pageNum]=r.stamps||[];notes[r.pageNum]=r.notes||[];history[r.pageNum]=[snapshot(r.pageNum)];historyIndex[r.pageNum]=0;}
			await tick();await renderPages();
		}catch(err){console.error(err);renderError='This PDF could not be opened. Try importing it again or opening a different copy.';}
		finally{renderBusy=false;}
	}
	function snapshot(p:number):Snapshot{return $state.snapshot({strokes:annotations[p]||[],stamps:stamps[p]||[],notes:notes[p]||[]});}
	function checkpoint(p:number){const h=history[p]||[],i=historyIndex[p]??-1,next=[...h.slice(0,i+1),snapshot(p)].slice(-80);history[p]=next;historyIndex[p]=next.length-1;save(p);}
	function save(p:number){void db.annotations.put($state.snapshot({id:`${score.id}_page_${p}`,scoreId:score.id,pageNum:p,strokes:annotations[p]||[],stamps:stamps[p]||[],notes:notes[p]||[]}));}
	function persistViewer(){localStorage.setItem(`sonora-viewer-${score.id}`,JSON.stringify({bookmarked,zoom,dual}));}

	async function renderPages(){
		if(!pdfDoc)return;renderId++;const id=renderId;renderBusy=true;renderError='';
		try{if(dual&&(host?.clientWidth||0)<760)dual=false;if(dual){const l=current%2===0?current:Math.max(1,current-1),r=l+1;await Promise.all([renderOne(l,leftPdf,leftInk,id),r<=pdfDoc.numPages?renderOne(r,rightPdf,rightInk,id):Promise.resolve()]);}else await renderOne(current,leftPdf,leftInk,id);}catch(err){console.error(err);if(id===renderId)renderError='Unable to render this page. Try Fit Page or a lower zoom.';}finally{if(id===renderId)renderBusy=false;}
	}
	async function renderOne(p:number,pdf:HTMLCanvasElement|null,ink:HTMLCanvasElement|null,id:number){
		if(!pdfDoc||!pdf||!ink||!host||p<1||p>pdfDoc.numPages)return;const page=await pdfDoc.getPage(p);if(id!==renderId)return;
		const base=page.getViewport({scale:1}),gap=dual?32:24,availableW=Math.max(280,dual?(host.clientWidth-gap-48)/2:host.clientWidth-48),availableH=Math.max(280,host.clientHeight-48);
		let scale=(fitMode==='width'?availableW/base.width:fitMode==='height'?availableH/base.height:Math.min(availableW/base.width,availableH/base.height))*zoom;const maxPixels=8_000_000;if(base.width*scale*base.height*scale>maxPixels)scale=Math.sqrt(maxPixels/(base.width*base.height));scale=Math.max(.2,Math.min(3,scale));
		const viewport=page.getViewport({scale}),w=Math.ceil(viewport.width),h=Math.ceil(viewport.height),dpr=Math.min(devicePixelRatio||1,2);pdf.width=w*dpr;pdf.height=h*dpr;ink.width=w*dpr;ink.height=h*dpr;pdf.style.width=ink.style.width=`${w}px`;pdf.style.height=ink.style.height=`${h}px`;
		const ctx=pdf.getContext('2d',{alpha:false})!,ictx=ink.getContext('2d')!;ctx.setTransform(dpr,0,0,dpr,0,0);ictx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;await page.render({canvasContext:ctx,viewport}).promise;if(id===renderId)redraw(p,ink);
	}

	function pagePoint(e:PointerEvent,c:HTMLCanvasElement){const r=c.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)),pressure:e.pressure>0?e.pressure:.5};}
	function px(p:{x:number;y:number},c:HTMLCanvasElement){const r=c.getBoundingClientRect();return{x:p.x*r.width,y:p.y*r.height};}
	function smoothPath(ctx:CanvasRenderingContext2D,points:{x:number;y:number}[],c:HTMLCanvasElement){if(!points.length)return;const first=px(points[0],c);ctx.beginPath();ctx.moveTo(first.x,first.y);if(points.length===1){ctx.arc(first.x,first.y,1,0,Math.PI*2);return;}for(let i=1;i<points.length-1;i++){const a=px(points[i],c),b=px(points[i+1],c),m={x:(a.x+b.x)/2,y:(a.y+b.y)/2};ctx.quadraticCurveTo(a.x,a.y,m.x,m.y);}const last=px(points.at(-1)!,c);ctx.quadraticCurveTo(last.x,last.y,last.x,last.y);}
	function redraw(p:number,c:HTMLCanvasElement|null=pageCanvas(p)){if(!c)return;const ctx=c.getContext('2d')!,r=c.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);for(const s of annotations[p]||[]){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';if(s.kind==='line'||s.kind==='arrow'){const a=px(s.points[0],c),b=px(s.points.at(-1)!,c);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=s.color;ctx.lineWidth=s.width;ctx.stroke();if(s.kind==='arrow'){const angle=Math.atan2(b.y-a.y,b.x-a.x),head=Math.max(8,s.width*4);ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-head*Math.cos(angle-.5),b.y-head*Math.sin(angle-.5));ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-head*Math.cos(angle+.5),b.y-head*Math.sin(angle+.5));ctx.stroke();}}else{smoothPath(ctx,s.points,c);ctx.strokeStyle=s.tool==='highlighter'?s.color+'66':s.color;ctx.lineWidth=s.tool==='highlighter'?Math.max(12,s.width*5):s.width;ctx.globalCompositeOperation=s.tool==='highlighter'?'multiply':'source-over';ctx.stroke();}ctx.restore();}for(const s of stamps[p]||[]){const q=px({x:s.x,y:s.y},c);ctx.save();ctx.font=`${s.fontSize}px LelandText, Leland, serif`;ctx.fillStyle=s.color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(s.symbol,q.x,q.y);ctx.restore();}}
	function pageCanvas(p:number){if(!dual)return leftInk;const l=current%2===0?current:Math.max(1,current-1);return p===l?leftInk:rightInk;}

	let drawing:{page:number;canvas:HTMLCanvasElement;stroke?:Stroke;pointerId:number;raf:number}|null=null;
	function scheduleRedraw(p:number,c:HTMLCanvasElement){if(!drawing||drawing.raf)return;drawing.raf=requestAnimationFrame(()=>{if(drawing)drawing.raf=0;redraw(p,c);});}
	function startAnnotation(e:PointerEvent,p:number,c:HTMLCanvasElement){
		if(readingMode||!annotationOpen||tool==='move')return;e.preventDefault();c.setPointerCapture(e.pointerId);const pt=pagePoint(e,c);
		if(tool==='symbol'){if(selectedSymbol)addSymbolAt(selectedSymbol,pt,p,c);return;}
		if(tool==='text'){const n:TextNote={id:crypto.randomUUID(),x:pt.x,y:pt.y,text:'',color,fontSize:16};(notes[p]||=[]).push(n);checkpoint(p);setTimeout(()=>document.getElementById(`note-${n.id}`)?.focus(),40);return;}
		if(tool==='eraser'){drawing={page:p,canvas:c,pointerId:e.pointerId,raf:0};eraseAt(pt,p,c);const move=(me:PointerEvent)=>{for(const ev of me.getCoalescedEvents?.()||[me])eraseAt(pagePoint(ev,c),p,c)};const finish=()=>{c.removeEventListener('pointermove',move);c.removeEventListener('pointerup',finish);c.removeEventListener('pointercancel',finish);drawing=null;try{c.releasePointerCapture(e.pointerId)}catch{}};c.addEventListener('pointermove',move,{passive:false});c.addEventListener('pointerup',finish,{once:true});c.addEventListener('pointercancel',finish,{once:true});return;}
		const kind=tool==='highlighter'?'highlighter':tool==='line'?'line':tool==='arrow'?'arrow':'freehand';const s:Stroke={id:crypto.randomUUID(),tool:tool==='highlighter'?'highlighter':'pen',color,width:strokeWidth,points:[pt],kind};(annotations[p]||=[]).push(s);drawing={page:p,canvas:c,stroke:s,pointerId:e.pointerId,raf:0};
		const move=(me:PointerEvent)=>{if(!drawing||drawing.stroke!==s)return;for(const ev of me.getCoalescedEvents?.()||[me])s.points.push(pagePoint(ev,c));scheduleRedraw(p,c);};
		const finish=()=>{if(!drawing||drawing.stroke!==s)return;c.removeEventListener('pointermove',move);c.removeEventListener('pointerup',finish);c.removeEventListener('pointercancel',finish);if(drawing.raf)cancelAnimationFrame(drawing.raf);drawing=null;try{c.releasePointerCapture(e.pointerId)}catch{}if(s.points.length>1)checkpoint(p);redraw(p,c);};
		c.addEventListener('pointermove',move,{passive:false});c.addEventListener('pointerup',finish,{once:true});c.addEventListener('pointercancel',finish,{once:true});
	}
	function eraseAt(pt:{x:number;y:number},p:number,c:HTMLCanvasElement){const radius=Math.max(.009,strokeWidth/900),oldA=(annotations[p]||[]).length,oldS=(stamps[p]||[]).length;annotations[p]=(annotations[p]||[]).filter(s=>!s.points.some(q=>Math.hypot(q.x-pt.x,q.y-pt.y)<radius));stamps[p]=(stamps[p]||[]).filter(s=>Math.hypot(s.x-pt.x,s.y-pt.y)>radius*2);if(oldA!==(annotations[p]||[]).length||oldS!==(stamps[p]||[]).length){redraw(p,c);checkpoint(p);}}
	function addSymbolAt(s:MusicSymbol,pt:{x:number;y:number},p:number,c:HTMLCanvasElement){(stamps[p]||=[]).push({id:crypto.randomUUID(),x:pt.x,y:pt.y,symbol:s.glyph,label:s.name,color,fontSize:34});checkpoint(p);redraw(p,c);selectedSymbol=null;tool='move';}
	function chooseSymbol(s:MusicSymbol){selectedSymbol=s;tool='symbol';symbolsOpen=false;annotationOpen=true;}
	function restore(p:number,s:Snapshot){annotations[p]=JSON.parse(JSON.stringify(s.strokes));stamps[p]=JSON.parse(JSON.stringify(s.stamps));notes[p]=JSON.parse(JSON.stringify(s.notes));save(p);redraw(p);}
	function undo(){const p=current,i=historyIndex[p]??0;if(i>0){historyIndex[p]=i-1;restore(p,history[p][i-1]);}}
	function redo(){const p=current,i=historyIndex[p]??0;if(history[p]&&i<history[p].length-1){historyIndex[p]=i+1;restore(p,history[p][i+1]);}}
	function nav(d:number){const max=pdfDoc?.numPages||1,step=dual?2:1,n=current+d*step;if(n>=1&&n<=max){current=n;pageInput=String(n);void renderPages();}}
	function goToPage(){const max=pdfDoc?.numPages||1,n=Math.max(1,Math.min(max,Number(pageInput)||1));current=n;pageInput=String(n);void renderPages();}
	function setZoom(v:number){zoom=Math.max(.5,Math.min(2.5,v));fitMode='free';persistViewer();void renderPages();}
	function fit(m:FitMode){fitMode=m;if(m!=='free')zoom=1;void renderPages();}
	function toggleBookmark(){bookmarked=!bookmarked;persistViewer();}
	function deleteNote(p:number,id:string){notes[p]=(notes[p]||[]).filter(n=>n.id!==id);checkpoint(p);}

	async function ensureAudio(){if(!audioContext)audioContext=new AudioContext();if(audioContext.state==='suspended')await audioContext.resume();}
	function tickSound(){if(!audioContext)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=metronomeBeat===0?1000:700;g.gain.setValueAtTime(.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.16,audioContext.currentTime+.005);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.045);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.05);}
	async function toggleMetronome(){if(metronomeRunning){stopMetronome();return;}await ensureAudio();metronomeRunning=true;metronomeBeat=0;tickSound();metroTimer=setInterval(()=>{metronomeBeat=(metronomeBeat+1)%4;tickSound();},60000/metronomeBpm);}
	function stopMetronome(){metronomeRunning=false;if(metroTimer){clearInterval(metroTimer);metroTimer=undefined;}}
	function changeBpm(v:number){metronomeBpm=Math.max(30,Math.min(240,metronomeBpm+v));if(metronomeRunning){stopMetronome();void toggleMetronome();}}
	function frequencyToNote(f:number){const n=69+12*Math.log2(f/440),midi=Math.round(n),names=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];return{name:`${names[(midi+1200)%12]}${Math.floor(midi/12)-1}`,cents:Math.round((n-midi)*100)};}
	async function toggleTuner(){if(tunerRunning){stopTuner();return;}tunerError='';try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});tunerStream=stream;await ensureAudio();analyser=audioContext!.createAnalyser();analyser.fftSize=4096;audioContext!.createMediaStreamSource(stream).connect(analyser);tunerRunning=true;readTuner();}catch{tunerError='Microphone access was denied or is unavailable.';}}
	function readTuner(){if(!tunerRunning||!analyser)return;const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);let rms=0;for(const v of data)rms+=v*v;rms=Math.sqrt(rms/data.length);if(rms>.012){let bestLag=0,bestCorr=0;for(let lag=20;lag<1000;lag+=2){let corr=0;for(let i=0;i<data.length-lag;i+=4)corr+=data[i]*data[i+lag];if(corr>bestCorr){bestCorr=corr;bestLag=lag;}}if(bestLag){const f=audioContext!.sampleRate/bestLag;if(f>60&&f<1600){const n=frequencyToNote(f);tunerFrequency=Math.round(f);tunerNote=n.name;tunerCents=n.cents;}}}tunerFrame=requestAnimationFrame(readTuner);}
	function stopTuner(){tunerRunning=false;if(tunerFrame)cancelAnimationFrame(tunerFrame);tunerStream?.getTracks().forEach(t=>t.stop());tunerStream=null;analyser=null;}
	function key(e:KeyboardEvent){if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(e.key==='Escape'){settingsOpen=false;symbolsOpen=false;utility='none';selectedSymbol=null;tool='move';if(readingMode){readingMode=false;controlsVisible=true;}}else if(e.key==='ArrowRight'||e.key==='PageDown'||e.key===' '){e.preventDefault();nav(1);}else if(e.key==='ArrowLeft'||e.key==='PageUp')nav(-1);else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(e.key.toLowerCase()==='p'){annotationOpen=true;tool='pen';}else if(e.key.toLowerCase()==='h'){annotationOpen=true;tool='highlighter';}else if(e.key.toLowerCase()==='e'){annotationOpen=true;tool='eraser';}}
</script>

<svelte:window onkeydown={key} onresize={()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>void renderPages(),180)}} />
<div class="fixed inset-0 z-50 flex flex-col overflow-hidden bg-[#11110f] text-neutral-100 font-sans">
	{#if controlsVisible&&!readingMode}<header class="shrink-0 h-16 border-b border-white/8 bg-[#171714]/95 backdrop-blur-xl flex items-center justify-between gap-2 px-3 sm:px-5"><div class="flex items-center gap-2 min-w-0 flex-1"><button class="h-11 w-11 shrink-0 rounded-2xl flex items-center justify-center hover:bg-white/8" onclick={onClose}><ArrowLeft size={20}/></button><div class="hidden sm:block min-w-0"><div class="text-sm font-semibold truncate">{score.title}</div><div class="text-xs text-neutral-500 truncate">{score.composer}</div></div></div><div class="flex items-center gap-1 rounded-2xl bg-[#0d0d0b] border border-white/8 p-1"><button class="h-10 w-10 rounded-xl hover:bg-white/8 disabled:opacity-30" disabled={current<=1} onclick={()=>nav(-1)}><ChevronLeft size={20}/></button><div class="min-w-20 h-10 px-2 flex items-center justify-center text-sm tabular-nums">{current}<span class="text-xs text-neutral-500 ml-1">/ {pdfDoc?.numPages||'…'}</span></div><button class="h-10 w-10 rounded-xl hover:bg-white/8 disabled:opacity-30" disabled={current>=(pdfDoc?.numPages||1)} onclick={()=>nav(1)}><ChevronRight size={20}/></button></div><div class="flex items-center justify-end gap-1 flex-1"><button class="h-11 w-11 rounded-2xl hover:bg-white/8 {bookmarked?'text-amber-400':''}" onclick={toggleBookmark}>{#if bookmarked}<BookmarkCheck size={19}/>{:else}<Bookmark size={19}/>{/if}</button><button class="h-11 w-11 rounded-2xl {annotationOpen?'bg-violet-600 text-white':'hover:bg-white/8'}" onclick={()=>annotationOpen=!annotationOpen}><PenTool size={19}/></button><button class="h-11 w-11 rounded-2xl hover:bg-white/8" onclick={()=>utility=utility==='metronome'?'none':'metronome'}><Timer size={19}/></button><button class="h-11 w-11 rounded-2xl hover:bg-white/8" onclick={()=>utility=utility==='tuner'?'none':'tuner'}><Mic2 size={19}/></button><button class="h-11 w-11 rounded-2xl hover:bg-white/8 hidden sm:flex" onclick={()=>{dual=!dual;void renderPages()}}><BookOpen size={19}/></button><button class="h-11 w-11 rounded-2xl hover:bg-white/8" onclick={()=>{readingMode=true;controlsVisible=false}}><Maximize2 size={18}/></button><button class="h-11 w-11 rounded-2xl {settingsOpen?'bg-white/10':'hover:bg-white/8'}" onclick={()=>settingsOpen=!settingsOpen}><Settings2 size={19}/></button></div></header>{/if}
	{#if controlsVisible&&!readingMode&&annotationOpen}<div class="absolute z-30 left-1/2 -translate-x-1/2 bottom-4 sm:bottom-6 flex items-center gap-1.5 rounded-3xl border border-white/10 bg-[#191916]/97 backdrop-blur-2xl shadow-2xl p-2 max-w-[calc(100vw-16px)] overflow-x-auto">{@render toolButton('move',MousePointer2,'Move')}{@render toolButton('pen',PenTool,'Pen')}{@render toolButton('highlighter',Highlighter,'Highlight')}{@render toolButton('line',Minus,'Line')}{@render toolButton('arrow',ArrowUpRight,'Arrow')}{@render toolButton('text',Type,'Text')}{@render toolButton('eraser',Eraser,'Erase')}<button class="h-11 px-3 rounded-2xl {symbolsOpen||tool==='symbol'?'bg-violet-600 text-white':'hover:bg-white/8'} flex items-center gap-2 shrink-0" onclick={()=>symbolsOpen=true}><Grid3X3 size={18}/><span class="hidden lg:inline text-xs">Symbols</span></button><div class="w-px h-7 bg-white/10 shrink-0"/>{#each colors as c}<button aria-label="Annotation color" class="h-7 w-7 rounded-full shrink-0 ring-2 ring-offset-2 ring-offset-[#191916] {color===c?'ring-white':'ring-transparent'}" style:background-color={c} onclick={()=>color=c}/>{/each}<input aria-label="Stroke width" type="range" min="1" max="12" bind:value={strokeWidth} class="w-20 accent-violet-500 shrink-0"/><button class="h-11 w-11 rounded-2xl hover:bg-white/8 disabled:opacity-30 shrink-0" onclick={undo} disabled={(historyIndex[current]??0)<=0}><Undo2 size={18}/></button><button class="h-11 w-11 rounded-2xl hover:bg-white/8 disabled:opacity-30 shrink-0" onclick={redo} disabled={!history[current]||(historyIndex[current]??0)>=history[current].length-1}><Redo2 size={18}/></button></div>{/if}
	{#if symbolsOpen}<div class="absolute z-50 inset-x-3 sm:left-1/2 sm:-translate-x-1/2 sm:w-[700px] bottom-20 max-h-[72vh] rounded-3xl border border-white/10 bg-[#191916]/98 backdrop-blur-2xl shadow-2xl p-4 overflow-hidden"><div class="flex items-center justify-between mb-3"><div><h2 class="font-semibold">Musical symbols</h2><p class="text-xs text-neutral-500">Choose a symbol, then tap the score where you want to place it.</p></div><button class="h-10 w-10 rounded-xl hover:bg-white/8" onclick={()=>symbolsOpen=false}><X size={18}/></button></div><div class="flex gap-1 overflow-x-auto pb-2 mb-2">{#each MUSIC_SYMBOL_CATEGORIES as category}<button class="px-3 h-9 rounded-xl text-xs whitespace-nowrap {selectedSymbolCategory===category?'bg-violet-600 text-white':'hover:bg-white/8 text-neutral-400'}" onclick={()=>selectedSymbolCategory=category}>{category}</button>{/each}</div><div class="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 gap-2 overflow-y-auto max-h-[48vh] pr-1">{#each MUSIC_SYMBOLS.filter(s=>s.category===selectedSymbolCategory) as s}<button class="aspect-square rounded-2xl bg-white/5 hover:bg-violet-500/15 border border-white/5 hover:border-violet-500/40 flex flex-col items-center justify-center gap-1 transition" onclick={()=>chooseSymbol(s)}><span class="text-4xl leading-none music-symbol">{s.glyph}</span><span class="text-[9px] text-neutral-500 text-center px-1">{s.name}</span></button>{/each}</div></div>{/if}
	{#if utility==='metronome'}<div class="absolute z-40 top-20 right-3 w-[min(320px,calc(100vw-24px))] rounded-3xl border border-white/10 bg-[#191916]/98 backdrop-blur-2xl shadow-2xl p-5"><div class="flex justify-between items-center"><div><h2 class="font-semibold">Metronome</h2><p class="text-xs text-neutral-500">Practice with a steady click.</p></div><button class="h-9 w-9 rounded-xl hover:bg-white/8" onclick={()=>utility='none'}><X size={17}/></button></div><div class="text-center py-5"><div class="text-5xl font-semibold tabular-nums">{metronomeBpm}</div><div class="text-xs text-neutral-500 mt-1">BPM</div><div class="flex justify-center items-center gap-3 mt-4"><button class="h-11 w-11 rounded-xl bg-white/7" onclick={()=>changeBpm(-5)}><MinusCircle size={18}/></button><input aria-label="BPM" type="range" min="30" max="240" bind:value={metronomeBpm} class="w-40 accent-violet-500"/><button class="h-11 w-11 rounded-xl bg-white/7" onclick={()=>changeBpm(5)}><Plus size={18}/></button></div><div class="flex justify-center gap-2 mt-5">{#each [0,1,2,3] as b}<div class="w-3 h-3 rounded-full {metronomeRunning&&metronomeBeat===b?'bg-violet-400':'bg-white/15'}"></div>{/each}</div><button class="mt-5 w-full h-12 rounded-2xl {metronomeRunning?'bg-white/10':'bg-violet-600'}" onclick={()=>void toggleMetronome()}>{metronomeRunning?'Stop':'Start metronome'}</button></div></div>{/if}
	{#if utility==='tuner'}<div class="absolute z-40 top-20 right-3 w-[min(320px,calc(100vw-24px))] rounded-3xl border border-white/10 bg-[#191916]/98 backdrop-blur-2xl shadow-2xl p-5"><div class="flex justify-between items-center"><div><h2 class="font-semibold">Tuner</h2><p class="text-xs text-neutral-500">Use your microphone to tune.</p></div><button class="h-9 w-9 rounded-xl hover:bg-white/8" onclick={()=>{stopTuner();utility='none'}}><X size={17}/></button></div><div class="py-6 text-center"><div class="text-6xl font-semibold">{tunerNote}</div><div class="text-sm text-neutral-500 mt-2">{tunerFrequency?`${tunerFrequency} Hz`:'Play a note'}</div><div class="mt-5"><div class="relative h-3 rounded-full bg-white/8"><div class="absolute left-1/2 -translate-x-1/2 top-[-4px] h-5 w-0.5 bg-white/70"></div><div class="absolute top-0 h-3 w-2 rounded-full bg-violet-400 transition-all" style:left={`calc(50% + ${Math.max(-45,Math.min(45,tunerCents/2))}%)`}></div></div><div class="text-sm mt-3 tabular-nums">{tunerCents>0?'+':''}{tunerCents} cents</div></div>{#if tunerError}<p class="text-xs text-red-300 mt-3">{tunerError}</p>{/if}<button class="mt-5 w-full h-12 rounded-2xl {tunerRunning?'bg-white/10':'bg-violet-600'}" onclick={()=>void toggleTuner()}>{tunerRunning?'Stop tuner':'Start tuner'}</button></div></div>{/if}
	{#if settingsOpen&&controlsVisible&&!readingMode}<div class="absolute z-40 top-[4.25rem] right-3 w-[min(360px,calc(100vw-24px))] rounded-3xl border border-white/10 bg-[#1a1a17]/98 backdrop-blur-2xl shadow-2xl p-4"><div class="flex items-center justify-between mb-4"><div><h2 class="font-semibold">Viewer settings</h2><p class="text-xs text-neutral-500">Tune the score for your screen.</p></div><button class="h-9 w-9 rounded-xl hover:bg-white/8" onclick={()=>settingsOpen=false}><X size={17}/></button></div><div class="grid grid-cols-3 gap-1.5 mb-4">{#each [['page','Page'],['width','Width'],['height','Height']] as [id,label]}<button class="rounded-xl py-2.5 border {fitMode===id?'border-violet-500 bg-violet-500/15':'border-white/8 bg-white/5'}" onclick={()=>fit(id as FitMode)}>{label}</button>{/each}</div><label class="flex justify-between py-2">Two-page view<input type="checkbox" bind:checked={dual} onchange={()=>void renderPages()}/></label><p class="text-xs text-neutral-500 mt-3">Large pages are automatically capped to a safe pixel budget for tablets.</p></div>{/if}
	<main bind:this={host} class="flex-1 min-h-0 overflow-auto bg-[radial-gradient(circle_at_top,#262620_0%,#11110f_55%)] flex items-center justify-center p-3 sm:p-6" style="touch-action:pan-x pan-y pinch-zoom"><div class="flex items-center justify-center gap-4 sm:gap-8 min-h-full"><div class="relative bg-white rounded-sm overflow-hidden shadow-[0_22px_60px_rgba(0,0,0,.5)] ring-1 ring-black/20" style="touch-action:none"><canvas bind:this={leftPdf} class="block"/><canvas bind:this={leftInk} class="absolute inset-0 z-10 w-full h-full {tool==='move'?'cursor-grab':'cursor-crosshair'}" onpointerdown={(e)=>startAnnotation(e,dual?(current%2===0?current:Math.max(1,current-1)):current,leftInk!)}/>{#if renderBusy}<div class="absolute inset-0 bg-white/20 animate-pulse pointer-events-none"></div>{/if}{#if renderError}<div class="absolute inset-0 flex items-center justify-center bg-black/60 text-center p-6"><div class="max-w-xs"><p class="font-medium">Unable to display this page</p><p class="text-xs text-neutral-300 mt-2">{renderError}</p><button class="mt-4 px-4 py-2 rounded-xl bg-violet-600" onclick={()=>void renderPages()}>Retry</button></div></div>{/if}</div>{#if dual&&current+1<=(pdfDoc?.numPages||1)}<div class="relative bg-white rounded-sm overflow-hidden shadow-[0_22px_60px_rgba(0,0,0,.5)] ring-1 ring-black/20 hidden md:block" style="touch-action:none"><canvas bind:this={rightPdf} class="block"/><canvas bind:this={rightInk} class="absolute inset-0 z-10 w-full h-full cursor-crosshair" onpointerdown={(e)=>startAnnotation(e,current+1,rightInk!)}/></div>{/if}</div></main>
	{#if !controlsVisible||readingMode}<button class="absolute z-50 top-3 left-3 h-11 w-11 rounded-2xl bg-black/45 backdrop-blur border border-white/10 flex items-center justify-center" onclick={()=>{controlsVisible=true;readingMode=false}}><PanelLeft size={18}/></button>{/if}
	{#if controlsVisible&&!readingMode}<footer class="shrink-0 h-12 border-t border-white/7 bg-[#171714]/95 backdrop-blur-xl flex items-center justify-between px-3 sm:px-5 text-xs text-neutral-500"><div>{score.totalPages} pages · {Math.round(zoom*100)}%</div><form class="flex items-center gap-1" onsubmit={(e)=>{e.preventDefault();goToPage()}}><input bind:value={pageInput} inputmode="numeric" aria-label="Page number" class="w-12 h-8 text-center rounded-lg bg-white/5 border border-white/8 text-neutral-200"/><span>/ {pdfDoc?.numPages||'…'}</span><button type="button" class="h-8 px-2 rounded-lg hover:bg-white/7" onclick={()=>fit('page')}>Fit</button></form><div class="hidden sm:flex items-center gap-1"><button class="h-8 w-8 rounded-lg hover:bg-white/7" onclick={()=>setZoom(zoom-.1)}><ZoomOut size={15}/></button><button class="h-8 w-8 rounded-lg hover:bg-white/7" onclick={()=>setZoom(zoom+.1)}><ZoomIn size={15}/></button></div></footer>{/if}
</div>
{#snippet toolButton(id:Tool,Icon:any,label:string)}<button class="h-11 px-2.5 min-w-11 rounded-2xl flex items-center justify-center gap-1.5 shrink-0 {tool===id?'bg-violet-600 text-white shadow-lg':'text-neutral-300 hover:bg-white/8'}" onclick={()=>{tool=id;selectedSymbol=null}} title={label}><Icon size={18}/><span class="hidden lg:inline text-xs">{label}</span></button>{/snippet}
<style>
	@font-face{font-family:Leland;src:url('/Leland.otf') format('opentype');font-display:swap}
	@font-face{font-family:LelandText;src:url('/LelandText.otf') format('opentype');font-display:swap}
	.music-symbol{font-family:LelandText,Leland,serif}
</style>
